### ISSUE TITLE
ROS2 Gem - "Robot Importer" icon is missing

### ISSUE THREAD

**Issue by pawelbudziszewski** [o3de/o3de-extras#100]
There used to be an icon for "Robot Importer" toolbar and menu items. It must have been lost during the migration.
![Screenshot from 2023-01-18 12-04-10](https://user-images.githubusercontent.com/31925544/213160134-aedea850-fa11-49b0-ba6b-cb5f264bebe0.png)

**Comment by lgleim** [comment]
@spham-amzn Is this something you would know how to address?

**Comment by pawelbudziszewski** [comment]
Just a comment from my side: 
The icon: https://github.com/o3de/o3de-extras/tree/development/Gems/ROS2/Assets/Editor/Images/Icons
The button (which should have the icon):
https://github.com/o3de/o3de-extras/blob/development/Gems/ROS2/Code/Source/RobotImporter/ROS2RobotImporterEditorSystemComponent.cpp
As far as I can tell, this looks correct. But the icon doesn't show...
