### ISSUE TITLE
Migrate o3de-physics-test-scene repo from RobotecAI to O3DE-Extras repo

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de-extras#104]
It would be great to migrate [o3de-physics-test-scene](https://github.com/RobotecAI/o3de-physics-test-scene) from the [RobotecAI](https://github.com/RobotecAI) organization to the O3DE Extras repo.

Tagging @adamdbrw, @michalpelka, @pawelbudziszewski and @spham-amzn (as well as @lumberyard-employee-dm) who have experience migrating repos between organizations as happened with the ROS2 Gem.

**Comment by adamdbrw** [comment]
@hultonha I believe that the repo is migrated now, closing this issue.
