### ISSUE TITLE
Editor gets stuck at "Asset Processor Working"

### ISSUE THREAD

**Issue by danielemorra98** [o3de/o3de-extras#107]
**Describe the bug**
When launching the Editor, it remains stuck with the "Asset Processor Working". The asset Processor window does not open. I think this could relate to the [ROS2 Gem](https://github.com/o3de/o3de-extras/tree/development/Gems/ROS2) which is registered to the project I am attempting to launch.

It never happened to me. It looks like there is some connection issue. On the terminal it shows me:
```
AssetProcessorConnection: Network connection attempt failure, Connect returned error AzSockError::eASE_ECONNREFUSED
```

In fact, if I terminate the execution by `Ctrl+C` the Editor view pops up. Anyway, when I play it crashes and it throw out the following error:

```
terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
  what():  could not create subscription: rcl node's context is invalid, at /tmp/binarydeb/ros-galactic-rcl-3.1.4/src/rcl/node.c:426
```

It has sometimes happened to me since I switched working on a virtual desktop through NoMachine. When I used physically the same workstation it never happened. 
The only way to make it work again is to shut down the virtual session and start up a new one.

**Actual behavior**
Launching routine gets stuck at "Asset Processor Working". If I press Ctrl+C the engine starts up but it will crash if I run the simulation.

**Found in Branch**
o3de: branch `development` commit `57a500f3eaf2b0d8450003dd04016f5147e940a7`
o3de-extras (ROS2 Gem): branch `development` commit `6350192c054188122bc12be767f3f1c80ae6fe77`

**Desktop/Device (please complete the following information):**
 - Device: Workstation
 - OS: Linux
 - Version: Focal - 20.04
 - CPU: 11th Gen Intel Core i9-11900K
 - GPU: NVIDIA RTX A5000
 - Memory: 64 Gb

**Comment by adamdbrw** [comment]
> terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
>   what():  could not create subscription: rcl node's context is invalid,

This is expected since you pressed Ctrl-C, which shutdowns ROS and invalidates the context. However, considering this, perhaps O3DE could handle Ctrl-C differently to avoid such states.

This seems to be an issue with the AssetProcessor, perhaps affected by using a virtual desktop. Could you provide log files?

**Comment by danielemorra98** [comment]
Unfortunately (or fortunately) it has not happened anymore for the last three days. As soon as I face it again, I am going to provide the logs.

**Comment by lumberyard-employee-dm** [comment]
This may be an issue that when the AssetProcessor launchess with an empty Asset Cache `<project-path>/Cache` folder, that it tries to get proceed to initialize other Editor systems without processing all assets that are critcal
