### ISSUE TITLE
Restructure READMEs for robotics demos and templates

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de-extras#111]
Currently, the robotic demo projects are:
[Robot Vacuum](https://github.com/o3de/RobotVacuumSample)
[Apple-picking Robots](https://github.com/o3de/ROSConDemo)

Robotic templates are:
[Warehouse Fleet Template](https://github.com/o3de/o3de-extras/Templates/Ros2FleetRobotTemplate)
[Simple ROS Project Template](https://github.com/o3de/o3de-extras/Templates/Ros2ProjectTemplate)

Between these projects, the ROS 2 Gem and its [documentation](https://github.com/o3de/o3de.org/pull/2191), there is much in common in terms of dependencies for the Project and common pre-build steps. Some of these include:
- Acquiring and enabling the ROS 2 Gem.
- Installing ROS 2.
- Sourcing ROS 2.
- Troubleshooting related to ROS 2 issues and middleware.

To avoid repetition, this common content should be described in ROS 2 Gem / robotics documentation and only linked from the demos. To resolve this issue, please make sure that the entire process for each Demo is at least as clear as it was before.

**Comment by hultonha** [comment]
Tagging @chanmosq for visibility, this is something to discuss, please add any extra context here if needed. Thanks!

**Comment by adamdbrw** [comment]
I have updated the description to include Templates

**Comment by michalpelka** [comment]
Added to RosCon:
https://github.com/o3de/ROSConDemo/pull/251/files
