### ISSUE TITLE
Robotics Template: add sensor 3D model(s) to the robot

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de-extras#113]
Currently, the Husarion ROSBot XL which is used in the template has no attached sensor models, even though it has a (virtual) LIDAR sensor operating. 

This issue involves preparation of a LIDAR prefab and adding it to the robot prefab. LIDAR is to be selected, considering what is typical for this robot but also what would be best for a template user.

**Comment by michalpelka** [comment]
Added in #165
