### ISSUE TITLE
Unknown CMake command "o3de_find_ancestor_gem_root"

### ISSUE THREAD

**Issue by ngacarter1182** [o3de/o3de-extras#115]
Tried to make a basic setup, Ubuntu 22.04, a clone of this repo, the 22.10.0 Linux release of O3DE. Sourced the terminal, registered the gems, enabled the gem for the project and this log is the build fail result

cmake -B build/linux -S . -GNinja Multi-Config -DLY_3RDPARTY_PATH=/home/rise/.o3de/3rdParty
-- Using package /home/rise/.o3de/3rdParty/packages/zlib-1.2.11-rev5-linux
-- Using package /home/rise/.o3de/3rdParty/packages/qt-5.15.2-rev8-linux
-- Using package /opt/O3DE/22.10.0/python/runtime/python-3.10.5-rev2-linux
-- Using Python 3.10.5 at /opt/O3DE/22.10.0/python/runtime/python-3.10.5-rev2-linux/python/bin/python
-- Using package /home/rise/.o3de/3rdParty/packages/RapidJSON-1.1.0-rev1-multiplatform
-- Using package /home/rise/.o3de/3rdParty/packages/Lua-5.4.4-rev1-linux
-- Using package /home/rise/.o3de/3rdParty/packages/RapidXML-1.13-rev1-multiplatform
-- Using package /home/rise/.o3de/3rdParty/packages/zstd-1.35-multiplatform
-- Using package /home/rise/.o3de/3rdParty/packages/cityhash-1.1-multiplatform
-- Using package /home/rise/.o3de/3rdParty/packages/unwind-1.2.1-linux
-- Using package /home/rise/.o3de/3rdParty/packages/lz4-1.9.3-vcpkg-rev4-linux
-- Using package /home/rise/.o3de/3rdParty/packages/googletest-1.8.1-rev4-linux
-- Using package /home/rise/.o3de/3rdParty/packages/googlebenchmark-1.5.0-rev2-linux
-- Using package /home/rise/.o3de/3rdParty/packages/SQLite-3.37.2-rev1-linux
-- Using package /home/rise/.o3de/3rdParty/packages/expat-2.4.2-rev2-linux
-- Using package /home/rise/.o3de/3rdParty/packages/md5-2.0-multiplatform
-- Using package /home/rise/.o3de/3rdParty/packages/tiff-4.2.0.15-rev3-linux
-- Using package /home/rise/.o3de/3rdParty/packages/squish-ccr-deb557d-rev1-linux
-- Using package /home/rise/.o3de/3rdParty/packages/assimp-5.1.6-rev1-linux
-- Using package /home/rise/.o3de/3rdParty/packages/xxhash-0.7.4-rev1-multiplatform
-- Using package /home/rise/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-linux-openssl-1
-- Using package /home/rise/.o3de/3rdParty/packages/pybind11-2.10.0-rev1-multiplatform
-- Using package /home/rise/.o3de/3rdParty/packages/mcpp-2.7.2_az.2-rev1-linux
-- Using package /home/rise/.o3de/3rdParty/packages/DirectXShaderCompilerDxc-1.6.2112-o3de-rev1-linux
-- Using package /home/rise/.o3de/3rdParty/packages/SPIRVCross-2021.04.29-rev1-linux
-- Using package /home/rise/.o3de/3rdParty/packages/azslc-1.7.35-rev1-linux
-- Using package /home/rise/.o3de/3rdParty/packages/astc-encoder-3.2-rev2-linux
-- Using package /home/rise/.o3de/3rdParty/packages/ISPCTexComp-36b80aa-rev1-linux
-- Using package /home/rise/.o3de/3rdParty/packages/OpenEXR-3.1.3-rev4-linux
-- Using package /home/rise/.o3de/3rdParty/packages/openimageio-opencolorio-2.3.17-rev2-linux
-- Using package /home/rise/.o3de/3rdParty/packages/png-1.6.37-rev2-linux
-- Using package /home/rise/.o3de/3rdParty/packages/freetype-2.11.1-rev1-linux
-- Using package /home/rise/.o3de/3rdParty/packages/pyside2-5.15.2.1-py3.10-rev3-linux
-- Using package /home/rise/.o3de/3rdParty/packages/AWSGameLiftServerSDK-3.4.2-rev1-linux
-- Using package /home/rise/.o3de/3rdParty/packages/PhysX-4.1.2.29882248-rev5-linux
-- Using package /home/rise/.o3de/3rdParty/packages/poly2tri-7f0487a-rev1-linux
-- Using package /home/rise/.o3de/3rdParty/packages/v-hacd-2.3-1a49edf-rev1-linux
-- Using package /home/rise/.o3de/3rdParty/packages/libsamplerate-0.2.1-rev2-linux
-- Using package /home/rise/.o3de/3rdParty/packages/NvCloth-v1.1.6-4-gd243404-pr58-rev1-linux
-- Using package /home/rise/.o3de/3rdParty/packages/mikkelsen-1.0.0.4-linux
-- Using package /home/rise/.o3de/3rdParty/packages/OpenMesh-8.1-rev3-linux
CMake Error at /home/rise/Desktop/o3de-extras/Gems/ROS2/CMakeLists.txt:8 (o3de_find_ancestor_gem_root):
  Unknown CMake command "o3de_find_ancestor_gem_root".

-- Configuring incomplete, errors occurred!
See also "/home/rise/Desktop/TestProject/build/linux/CMakeFiles/CMakeOutput.log".
See also "/home/rise/Desktop/TestProject/build/linux/CMakeFiles/CMakeError.log".

**Comment by adamdbrw** [comment]
> the 22.10.0 Linux release of O3DE
The Gem does not work with the release version of the O3DE yet, only with the development branch (as per instructions). It will be supported in the next release.
