### ISSUE TITLE
Poor PhysX performances

### ISSUE THREAD

**Issue by danielemorra98** [o3de/o3de-extras#123]
**Bug description**
I have a scene with a 4-wheels vehicle on a simple box serving as a ground. The vehicle is controlled through Ackermann Controller. I have have two different setup (from now on COMPUTER-A and COMPUTER-B) in which I run the same simulation with the following difference:

COMPUTER-A has Ros2-Gem checked out at de2d1cdfa68310c6c0d885d65c0d62fa972a4a69 commit (1 dec)
COMPUTER-B  has Ros2-Gem checked out at ba6a13a0f013f7c58bf5039ea08cca391014f09a commit (10 oct)

With COMPUTER-A when I move the robot (through a custom teleop_twist_keyboard node) it does not look smooth, but it is  bouncing on the ground. That is something that **does not happen** with COMPUTER-B.

Did you modify the way the colliders and/or the Torque actuated on the wheels behave?

**Test environment**
Both COMPUTER-A and COMPUTER-B:
 - OS: Ubuntu 20.04
 - ROS: Galactic

COMPUTER-A:
 - CPU: Intel Xeon Gold 5218
 - GPU: Quadro RTX 5000     

COMPUTER-B:
 - CPU: 11th Gen Intel Core i9-11900K
 - GPU: NVIDIA RTX A5000

According to [this website](https://www.cpubenchmark.net/compare/3904vs3536/Intel-i9-11900K-vs-Intel-Xeon-Gold-5218)  the Xeon CPU has about 36% lower single-thread performance. However, I do not think this justifies the significant observed difference in performance.

**Comment by adamdbrw** [comment]
@danielemorra98 did you have some time to look into whether this happens in any of the demos with / without VehicleDynamics?

**Comment by danielemorra98** [comment]
@adamdbrw Unfortunately I cannot access to the machine anymore. I will ping you again in case I will be able to do in the future. My Apologies
