### ISSUE TITLE
URDF Import: support for texture specified by filename 

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de-extras#130]
**Is your feature request related to a problem? Please describe.**

Currently only specification of default materials with given colors is supported in URDF Importer. Textures are still supported if they are part of meshes. 

This task involves implementing texture_filename handling in mesh visual tags of urfdom.

**Comment by michalpelka** [comment]
Happy to close this issue :tada: due to those two, fine, contributions:
https://github.com/o3de/o3de-extras/pull/497
https://github.com/o3de/o3de-extras/pull/555
