### ISSUE TITLE
High resolution tick bus for sensors

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de-extras#133]
**Is your feature request related to a problem? Please describe.**
Currently, ROS2SensorComponent (and thus, all sensors) uses AZ::TickBus::Handler for sensor behavior. This is sufficient for some sensors such as LIDAR and camera, but some sensors need to operate at higher frequencies (in kHz). 

An important consideration is whether we are able to make measurement with such frequency, but we would like to enable such sensors if the user chooses to implement their behavior on top / aside of O3DE physics (compute with higher frequency than physics step).

**Comment by michalpelka** [comment]
We are using here AzPhysics::SceneEvents::OnSceneActiveSimulatedBodiesEvent::Handler.
https://github.com/o3de/o3de-extras/pull/221
https://github.com/o3de/o3de-extras/pull/220

**Comment by michalpelka** [comment]
Implemented #254
