### ISSUE TITLE
For some robots, Imported robot is static due to lack of inertial in base_link

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de-extras#137]
**Bug description**
I've tried to import a robot description from this file : 
https://github.com/husky/husky/blob/foxy-devel/husky_description/urdf/husky.urdf.xacro

**To Reproduce**
1. Checkout repository from Clearpath
2. Build ros2 workspace
3. Generate `husky.urdf` from husky.urdf.xacro with 'xacro'
4. Adjust path in `husky.urdf` to relative and copy to assets catalog 'mesh'
5. Import URDF
6. Start the simulation

**Expected behavior**
The robot should be dynamic, it seems to be static.

**What happened**
The structure of URDF is as follows:
![image](https://user-images.githubusercontent.com/3209244/197496772-8811ff1c-0946-483e-9e96-d549d4de5559.png)
The `base_link` node does not have a rigid body component. Its child called 'inetrial_link' has it instead. After adding rigid body component with a default config the whole robot becomes dynamic

**Test environment**
 - OS: e.g. Ubuntu 22.04
 - ROS: Humble

**Additional context**

**Comment by adamdbrw** [comment]
Has been resolved with SDF support changes and #481
