### ISSUE TITLE
Robot Importer - add to User Guide and add a class diagram

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de-extras#141]
**Is your feature request related to a problem? Please describe.**
It should be clear for the user how Robot Importer widget works and what are current limitations.

**Describe the solution you'd like**
A guide on how to import a robot.

**Additional context**
https://github.com/RobotecAI/o3de-ros2-gem/issues/163 work should reflect in this task.

**Comment by adamdbrw** [comment]
Class diagram is not necessary (we have doxy generated API docs). But the documentation of URDF import feature should be of high priority as it is missing from ROS 2 Gem docs at the moment. @hultonha could we increase the priority here?

**Comment by hultonha** [comment]
> Class diagram is not necessary (we have doxy generated API docs). But the documentation of URDF import feature should be of high priority as it is missing from ROS 2 Gem docs at the moment. @hultonha could we increase the priority here?

Absolutely, priority increased :+1:

**Comment by michalpelka** [comment]
It was done at some point in the o3de.org repo.
