### ISSUE TITLE
Improve URDF importer UX

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de-extras#148]
**Is your feature request related to a problem? Please describe.**
Importer is currently in a very basic state in terms of user experience. We would like to improve user experience when importing robots.

**Describe the solution you'd like**

- [x] The Importer GUI is neat and does not look like work in progress
- [x] Typical pathways (things existing, missing, some common errors) are handled well, reducing chance of running into unpleasant behavior.
- [x] The user is pointed to the Assets directory when importing
- [x] The robot is spawned in a reasonable place. Consider adding a camera to the robot (overhead) and moving viewport there after the import.
- [ ] After import, inform about heuristics-base choices made by the importer and provide checklist for the user to guide them in the process - such as adding sensors, making sure the robot drives in the simulation, checking materials etc.

**Describe alternatives you've considered**
Importing URDFs automatically. This, however, poses multiple problems since we would like user to be aware of domain mapping issues as well as some heuristic choices we have made during the import (such as deducing drive type and populating vehicle dynamics components based on wheels).

**Additional context**
Create subtask for each item when starting to work on it with this task as a meta-issue. Create issues also for tasks which will be outside of milestone 2 - they will be handled with lower priority.

**Comment by michalpelka** [comment]
Heuristic checks are needed
