### ISSUE TITLE
Visualise camera 

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de-extras#153]
Projection - so user knows where it is pointing.

1. Translucent square + rays
2. Preview window (optional, if it makes sense)

**Comment by michalpelka** [comment]
Is being implemented in #103.

**Comment by hultonha** [comment]
@michalpelka I just wanted to check if this issue can now be closed? I think the visual mesh for the camera was added in an earlier PR. Thanks!

**Comment by michalpelka** [comment]
Yes, it was added in #103 .
