### ISSUE TITLE
Support joint types in frames

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de-extras#158]
ROS2 Frame Component represent a ros2 frame of reference and is suitable to handle joint types between different modules / parts of a robot. It currently only supports static transformation which are suitable for rigidly attached components (e.g. lidar box). 

The type of transformation should also be decided based on the attached joint component (fixed joint - static, other joints - dynamic).

**Comment by michalpelka** [comment]
It was fixed with [#119](https://github.com/o3de/o3de-extras/pull/119)
