### ISSUE TITLE
Show full topic / frame names

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de-extras#159]
ROS2 Components use frame and topic names to describe communication parameters. This is abstracted to ROS2 Sensor Component. As things are currently, the user might be confused as to what are the topic / frame names, considering namespaces are added. 

To amend this, 

- [ ] add a non-editable field displaying full name. 
- [ ] display current namespace in ROS2Frames

**Comment by adamdbrw** [comment]
Note that this is very similar to #131 and could be handled by a similar (reusable) solution.

**Comment by arturkamieniecki** [comment]
This issue can be resolved with #458.
