### ISSUE TITLE
Feature request: physics - articulations

### ISSUE THREAD

**Issue by pawelbudziszewski** [o3de/o3de-extras#164]
Articulations are extremely useful for robotic simulations. The main benefit of articulations is better dynamic stability, especially with higher mass ratios. To test it I prepared a simple experiment in Unity, which supports standard PhysX joints as well as articulations.

The test was done using a model of the real robot (UR3). All masses and geometry were based on real data. The robot was created in 2 versions: as a chain of rigid bodies connected with joints and using articulated bodies and joints. In both cases, geometry and mass parameters were the same. No actuators were applied, only gravity. Both robots were slightly tilted so that they were not in equilibrium.

The 1st simulation shows the default timestep settings. The rigid-body-based robot (left-hand side) is highly unstable. The articulated robot (right-hand side) is perfectly stable. 

https://user-images.githubusercontent.com/31925544/217881386-b52b2364-b0d9-4c14-8a37-66b2fa7b69a5.mp4

![1_default_timestep](https://user-images.githubusercontent.com/31925544/217881433-2e74a6ff-f620-4c56-b541-65cc0f879ca0.png)

In the 2nd simulation, timesteps have been reduced by an order of magnitude. The rigid-body-based robot behaves much better, however, there are still some instabilities. The simulation at the same time runs noticeably slower. Reducing timesteps by another order of magnitude seems to help, although I'm not convinced, that the rigid-body-based robot is completely stable.

https://user-images.githubusercontent.com/31925544/217881548-4b0c4813-2a23-4990-9710-a364511a28dc.mp4

![2_short_timestep](https://user-images.githubusercontent.com/31925544/217881583-4d647085-64af-418c-bd2c-423fea50f015.png)

For sure there are some ways to improve the stability of rigid-body-based models that could help achieve stable simulation with higher timesteps  (like, for example, solver iterations in O3DE). However, I am convinced that their effectiveness is incomparably less than the use of articulations.

**Comment by adamdbrw** [comment]
This issue requires Articulation support in physics system, which I know is to be worked on soon. We will keep it here to track the effort of porting existing robotic components to work with Articulations.

**Comment by adamdbrw** [comment]
@hultonha do you think there is a need for this issue, considering it is covered by the work you have listed?
