### ISSUE TITLE
Feature Request: Components for Manipulators

### ISSUE THREAD

**Issue by danielemorra98** [o3de/o3de-extras#171]
Based on a discussion in #161 the logic for Control and Dynamics in manipulator simulations should be managed by different components in line with the principle of separation of concerns and to improve reusability. 
The [current developed component](url) manages both the computation of the control commands and the PhysX event requests to move the joints. 
Based on preliminary discussions, it appears beneficial to split this into two different components as follows:

1. Introducing a low-level `ManipulatorModelComponent` which would provide for different manipulators design models for effort/velocity-based control and would expose the PhysX API as suggested in this [comment](https://github.com/o3de/o3de-extras/pull/161/files#r1101489925)
2. Refactoring `ManipulatorControllerComponent` focus on high-level capabilities of the Controller, turning the current version of the Component which handles trajectories coming from [ROS2 FollowJointTrajectory](http://docs.ros.org/en/electric/api/control_msgs/html/action/FollowJointTrajectory.html) clients but) into one implementation of this interface but providing the possibility to implement [different control approaches](https://github.com/o3de/o3de-extras/pull/161/files#r1101258930) based on the same abstract controller component. 

A detailed proposal for implementation can be found in [this RFC](https://github.com/o3de/sig-simulation/issues/54)

**Comment by adamdbrw** [comment]
This issue should await for at least some Articulation work to be completed since it will depend on it.
