### ISSUE TITLE
Warehouse Project Template for robotics

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de-extras#180]
**Is your feature request related to a problem? Please describe.**
Project templates are useful for developers, for a quick start with a robotics project, for onboarding with robotic simulation in O3DE, and as a starting point for a tutorial. One of typical use-cases is mobile logistics featuring fulfillment center and a fleet of Autonomous Mobile Robots (AMRs). Creating a template for this use-case would allow users to develop their simulations faster.

**Describe the solution you'd like**
A project template including:
- [x] An Asset Gem with a relevant AMR
- [x] An Asset Gem featuring the environment, divided nicely into objects so that the user is able to quickly create new similar interiors.
- [x] A Project Template which includes necessary documentation on how to run it. 
- [x] Documentation of the scene creation process using the environment Asset Gem.
- [x] Documentation on how to run a simple simulation with the Template, featuring ros2 navigation packages and a small fleet of robots. 

In the future, a tutorial can be created around the template and the documentation for scene creation and fleet manager.

**Describe alternatives you've considered**
Some alternatives to represented use-case have been considered. It is actually only a matter of priorities since many templates can be implemented with time covering a wider area of robotic simulation applications.

**Additional context**
The template would be a good example to demonstrate how to scale up (e.g. using RoboMaker).

**Comment by michalpelka** [comment]
template PR: #186

**Comment by hultonha** [comment]
@adamdbrw @michalpelka is it now safe to close this issue now the Warehouse Project Template is merged?

**Comment by adamdbrw** [comment]
@hultonha This is an issue covering all the work with and around the template - I ticked 3 sub-tasks as completed since the work has been merged. The two remaining tasks are also tracked by #183 and #184.
