### ISSUE TITLE
Warehouse Project Template: the Robot Gem

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de-extras#181]
**Is your feature request related to a problem? Please describe.**
The Warehouse Project Template requires an Autonomous Mobile Robot (AMR). The model has to represent a modern robot that actually runs ros2, is applied for this use case, and be available on unburdened license fully compatible with O3DE. 

**Describe the solution you'd like**
A robot Gem including:
- A 3D model of real robot, very good quality.
- Included ROS 2 components so that the robot is functional when spawned / added to the scene.
- Default namespaces - the robot is intended as many-of in the scene.

The Amazon Proteus robot was considered to be the best fit.

**Describe alternatives you've considered**
We considered some other AMRs such as MiRs, but many of these are older models, or are still running ROS 1.

**Additional context**
This is a sub-task for the Warehouse Project Template. Relevant context: #180.

**Comment by hultonha** [comment]
Resolved by https://github.com/o3de/o3de-extras/pull/173
