### ISSUE TITLE
Warehouse Project Template: the Warehouse Gem

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de-extras#182]
**Is your feature request related to a problem? Please describe.**
The Warehouse Project Template requires the scene assets Gem. These assets will be used to compose and customize fulfillment center environments for robotic simulations.

**Describe the solution you'd like**
An asset Gem including:
- Multiple object typical for fulfillment center, including racks, boxes, carts, poles, lights etc.
- Correct naming
- Colliders in objects
- High quality

**Describe alternatives you've considered**
Considered re-using some assets from the Simple Robotics Template, but they are not photorealistic and not enough to build a  fulfillment center scene.

**Additional context**
This is a sub-task for the Warehouse Project Template. Relevant context: #180.

**Comment by hultonha** [comment]
Resolved by https://github.com/o3de/o3de-extras/pull/174
