### ISSUE TITLE
ROS Gem does not compile after latest ROS Humble update (Ubuntu Jammy)

### ISSUE THREAD

**Issue by pawelbudziszewski** [o3de/o3de-extras#198]
`ROS Control Toolbox` package from the latest ROS Humble update for Ubuntu Jammy prevents compilation of the ROS Gem.

The problem is with the package: `ros-humble-control-toolbox_2.2.0-1jammy.20230221.151227`. It seems, that the internal structure of the package has changed, eg. includes were moved to a different folder. They used to be in `/opt/ros/humble/include/control_toolbox/`, now it looks like this:

```shell
$ dpkg -L ros-humble-control-toolbox
[...]
/opt/ros/humble/include/control_toolbox/control_toolbox/dither.hpp
/opt/ros/humble/include/control_toolbox/control_toolbox/filters.hpp
/opt/ros/humble/include/control_toolbox/control_toolbox/limited_proxy.hpp
/opt/ros/humble/include/control_toolbox/control_toolbox/pid.hpp
[...]
```

There seem to be other errors as well.

If ROS2 is installed following the official ROS documentation, the `ROS Control Toolbox` will be updated automatically with the next Ubuntu update, so the problem is serious.

**Comment by michalpelka** [comment]
On the older version, the 2.12-jammy of ros-control problem is not existing.
