### ISSUE TITLE
XR images are very jittery on VR devices.

### ISSUE THREAD

**Issue by laoyigrace** [o3de/o3de-extras#201]
Currently, we use the streaming mode to stream the o3de application images started by the PC to the Oculus quest2. The main solution is to use the ALVR+SteamVR mode.
We found that the XR application developed using o3de was very jittery on Oculus Quest2 after streaming. This problem does not occur in applications developed using Unity or UE.
Do you know why?

**Comment by byrcolin** [comment]
moved to a discussion #214
