### ISSUE TITLE
Improve onbording experience with Ros2ProjectTemplate

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de-extras#246]
- [x] Add build dependencies and include them to ROS2 Gem.
- [x]  Simplify used Lidar on the default robot
- [x] Create multiple ~~version~~ variants of Husarion robot (e.g. with camera, with 3D LiDAR,  with 2D LiDAR)
- [x] Reword readme 
- [x] Change the Project Template so that there is an EditorSystemComponent and respective targets so that it is much easier for the user to create their own Editor Components.
- [x] Review and merge fixes: https://github.com/o3de/o3de-extras/pull/243 
Optional:
- [x] Hello world publisher (e.g. simple goal sender to nav2)
- [x] Add Docker script that brings up project created from template.

**Comment by adamdbrw** [comment]
Not only with this template:
Please include generated code for Editor components / targets / module.
Currently, if the user would like to add any Editor Component, their experience is quite difficult as they need to add cmake targets, define editor module, refactor out the components descriptors creation into module interface etc.

**Comment by rainbj** [comment]
- Curious if we are exposing version number anywhere in the UX for "Create multiple version of Husarion robot"?
- "Add build dependencies and include them to ROS2 Gem." Does this have any UX with it?

Thanks, Joshua - Sig-UI-UX chair O3DE

**Comment by michalpelka** [comment]
@rainbj , 
Version is not a best word, better is variant e.g.:
- RosbotXL with lidar 2D
- RosbotXL with lidar 3D
- RosbotXL with depth camera 
It can be done quickly with a prefab override system.

""Add build dependencies and include them to ROS2 Gem." Does this have any UX with it?"
We claim that Users can easily extend simulation with their ROS2 C++ code (our target here is robotics, system developers).
Without those dependencies, this task is not that straightforward. You are right, for the end-user of simulation, it makes no difference.

**Comment by michalpelka** [comment]
All bullet points are checked. Closing issue. Good job.
