### ISSUE TITLE
Ros2ProjectTemplate, poor performance 

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de-extras#261]
I suffer, poor performance using auto-generated scene from Ros2ProjectTemplate.
I have 35 fps with and without robot using FHD resolution.
Seems, there is some bottleneck.
My config:

    Device: PC
    OS: Ubuntu 22.04
    Version 22.04
    CPU 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    GPU GeForce RTX 3070 Mobile (520.56.06)
    Memory 64GB

**Comment by adamdbrw** [comment]
This has been addressed with #267
