### ISSUE TITLE
ROS2 Lidar Sensor - incorrect rotations

### ISSUE THREAD

**Issue by pawelbudziszewski** [o3de/o3de-extras#268]
There is a problem with the rotations of ROS2 Lidar sensor. If it is tilted, rays are generated incorrectly.

I placed a lidar on a robot and rotated it (the lidar) around the X axis by 45 deg:
![Screenshot from 2023-04-13 23-12-49](https://user-images.githubusercontent.com/31925544/231885499-a4ab9a65-f8f5-4ad5-a9fb-01d44b4e990b.png)

When the robot is rotating, the lidar behaves like this:

https://user-images.githubusercontent.com/31925544/231885450-5ea498f6-1aad-43ea-b0e3-974bccf82996.mp4

The problem affects ROS2 Lidar as well as 2D Lidar

**Comment by adamdbrw** [comment]
Interesting! Is the same issue there for both standard and RGL implementation?

**Comment by pawelbudziszewski** [comment]
@adamdbrw I have not checked RGL. 
The problem was caused by the calculation of ray's angles in LidarTemplateUtils.cpp. Should be solved by https://github.com/o3de/o3de-extras/pull/269
