### ISSUE TITLE
Refactor ROS2Sensor component data acquisition loops

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de-extras#295]
**Is your feature request related to a problem? Please describe.**
This is an enhancement to the architecture of current data acquisition mechanism in ROS2Sensor component as introduced with #254.

**Describe the solution you'd like**
I would like to increase encapsulation and reduce the amount of code that the implementer of ROS2Sensor subclass needs to be aware of in order to succeed. This involves replacing inheritance with composition where needed and implementing NVI for the loops if applicable.

**Additional context**
The dual mechanism is here because one (onTick()) is simpler and refers to Engine updates, and the second one (physics events) provides a higher-frequency, less-jittery data streams important for sensors such as IMU and Odometry.

**Comment by Antoni-Robotec** [comment]
The sensors update mechanism is similar to the ones in ROS Publishers, would be best to unify.

**Comment by adamdbrw** [comment]
This means, when working on this task, also look at non-sensor publishers such as JointState.
