### ISSUE TITLE
URDF Importer, non-well formated xacro causes crash

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de-extras#307]
The output of the XACRO file is not verified if it is valid URDF. 
It can cause UB on dereferencing null URDF-DOM.

**Comment by michalpelka** [comment]
Here is crashing xacro:
```
<?xml version='1.0'?>
<robot name="rosbot_xl" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:arg name="use_sim" default="false" />

  <xacro:include filename="$(find FOOO)/Bar.xacro"/>
	<naughty_tag><naughty_tag>
</robot>
```

**Comment by byrcolin** [comment]
This should have been closed by adding the fixes label in the description on the PR https://github.com/o3de/o3de-extras/pull/324, so I think this should just be manually closed.
