### ISSUE TITLE
ROS 2 Gem Support for Iron Irwini 

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de-extras#330]
Since a new ROS distro is about to be released (next week), we would like the Gem to stay modern and enable users to work with the newest distribution. This should be quite easy since this distro targets the same Ubuntu version.
- [x] Review change log (Iron on top of Humble) to analyze impactful changes. Consider the Gem, Templates and Demos.
- [x] Complete a fresh build with Iron sourced. Go through Project Setup as in the Interactivity / Robotics O3DE documentation.
- [x] Also test ROSCon Demo (go through the scenario as described in the demo project README).
- [x] Cast a PR to o3de.org documentation which adds support to Iron.
- [x] Cast a PR to ROSCon Demo to include Iron as an option. Also for the docker script.

**Comment by arturkamieniecki** [comment]
ROSCon Demo works with ROS2 Iron. Only the apple gathering cannot be checked in the main level due to the changes made in ROS 2 Gem, which are being implemented into ROSCon Demo in https://github.com/o3de/ROSConDemo/pull/240. Using this pr apple gathering can be checked in the playground level.

**Comment by arturkamieniecki** [comment]
I've created a PR to the o3de.org documentation adding support for Iron. https://github.com/o3de/o3de.org/pull/2421

**Comment by arturkamieniecki** [comment]
I've created a PR to the ROSCon Demo repository, modifying README.md files to include support for ROS 2 Iron (https://github.com/o3de/ROSConDemo/pull/248). At the moment of writing, there isn't an available docker image for ROS 2 Iron, so I haven't modified the docker script.
