### ISSUE TITLE
ROS2 Gem: do we need the message type field?

### ISSUE THREAD

**Issue by pawelbudziszewski** [o3de/o3de-extras#334]
In components where ROS topics are defined, there is a field called `Type`. It seems, that this field (as well as `TopicConfiguration.m_type`) is never used or even checked. The user can provide virtually anything which doesn't influence the type of created topic.

Do we need this field?
 
![Screenshot from 2023-05-16 16-43-43](https://github.com/o3de/o3de-extras/assets/31925544/b4cb7d71-bc6d-4421-ae4a-4d926ab580dc)

**Comment by lgleim** [comment]
We just discussed this in today's issue triage and the field should probably just be removed, as it does not appear to be used by the code.
