### ISSUE TITLE
Cannot build ROS2ProjectTemplate

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de-extras#349]
Freshly generated project complaints during compilation:
```
CMake Error at /home/michal/github/o3de-extras/Gems/RosRobotSample/CMakeLists.txt:24 (o3de_add_variant_dependencies_for_gem_dependencies):
  Unknown CMake command "o3de_add_variant_dependencies_for_gem_dependencies".
 ```

**Comment by lumberyard-employee-dm** [comment]
The `o3de_add_variant_dependencies_for_gem_dependencies` was added to development two weeks ago in this PR: https://github.com/o3de/o3de/pull/15937

@michalpelka Are you using an older o3de engine that doesn't contain the change?

**Comment by michalpelka** [comment]
@lumberyard-employee-dm, yes I am using the o3de engine (2305.0) that does not contain that change.

**Comment by AMZN-alexpete** [comment]
We could potentially modify the project template to be backwards compatible by checking the o3de version and don't use that function if the O3DE_VERSION_STRING is `2305.0`

**Comment by michalpelka** [comment]
It can be built against development.
