### ISSUE TITLE
Add validation and improve default configuration for PositionController components

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de-extras#373]
PositionController components are the ones implementing `JointsPositionControllerRequests`. Currently, these are `JointsArticulationControllerComponent` and `JointsPIDControllerComponent`.

Currently, these components do not validate entity hierarchy for presence nor count of necessary components. These causes the need for runtime validation and possibility for users to construct wrong hierarchies or input wrong PIDs.
- Collection of PIDs in JointsPIDControllerComponent should correspond to joint names in ROS2Frames down the hierarchy, in entities where there are also Hinge joints.
- JointsArticulationControllerComponent could validate presence of ArticulationLink components down the hierarchy.

This requires adding corresponding Editor components. One idea is to have them listen to system entity activate events, check whether the entity is a descendant, look into its components and collect such information. Or to query the hierarchy (e.g. _GetEntityAndAllDescendants_) after all entities are activated somehow.

**Comment by michalpelka** [comment]
Discussed in triage meeting, issue being resolved by @arturkamieniecki .

**Comment by arturkamieniecki** [comment]
Closed as completed.
