### ISSUE TITLE
For the Joint Trajectory action server, standardize returned error results.

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de-extras#375]
Currently, some ways of returning errors are not fully informative for the action client.
- Review the specification of action servers and `control_msgs::action::FollowJointTrajectory`.
- Correct the flow of results such as from cancellation or invalid goal.
For example, if the goal cannot be reached, first accept it, and then return a failure result. Currently it is rejected with `rclcpp_action::GoalResponse::REJECT,` which does not leave an information as to why.

**Comment by michalpelka** [comment]
Fixed with 386 by @lewandowskikacper .
