### ISSUE TITLE
Fix Robot Fleet template with the new development branch

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de-extras#380]
Currently, the main scene does not seem to load due to some issue with the _Warehouse.prefab_.

![image](https://github.com/o3de/o3de-extras/assets/16702721/e58a4a5c-0327-42fc-bd4f-6e89c1e1453c)

**Comment by michalpelka** [comment]
I failed to recreated : with o3de hash : 4648d06821994a0256d691598a5ddb0f216822f1

**Comment by michalpelka** [comment]
I do not experience it also :
o3de-extras: 17ddb04d467d82004f58b0bf0ca05d8bc7a30676
o3de: https://github.com/arturkamieniecki/o3de/commit/db14806d67a5e0209392122656fb943a91b3e6f6

**Comment by jhanca-robotecai** [comment]
Tested with the newest (as of today) o3de-extras `development` branch: 1a4573a8
o3de (develop from 6th of June): 02ec68a8
I did **not** experience any issues.

**Comment by jhanca-robotecai** [comment]
An issue in **Ros2ProjectTemplate**

![image](https://github.com/o3de/o3de-extras/assets/134940295/0872b04a-d030-4d07-8ab0-1715fa137a75)

o3de (develop from 6th of June): 02ec68a8
o3de-extras development branch: 17ddb04d467d82004f58b0bf0ca05d8bc7a30676

**Comment by michalpelka** [comment]
@jhanca-robotecai it is other error - json replace is not valid - it is easy fix. Please raise separate issue for that.

**Comment by jhanca-robotecai** [comment]
> Please raise a separate issue for that.

https://github.com/o3de/o3de-extras/issues/425

**Comment by lewandowskikacper** [comment]
I don't have this problem either on current development branches.


The error messages are about asset from "WarehouseAssets" Gem.
Removing this Gem from the project produced the same error for me.
Possibly, following https://development--o3deorg.netlify.app/docs/user-guide/interactivity/robotics/project-configuration/#registering-robotic-project-templates  could resolve the problem?
