### ISSUE TITLE
Standardizing to US english

### ISSUE THREAD

**Issue by arturkamieniecki** [o3de/o3de-extras#382]
Some words are not spelled according to the US English spelling, such as  ```Visualise``` in the ROS2SensorComponent. Contributing guidelines specify that the US English spelling should be applied.

**Comment by aquav3** [comment]
Can I take this one?

**Comment by arturkamieniecki** [comment]
> Can I take this one?

Feel free to contribute. 
Make sure to follow the O3DE [contributing guidelines](https://github.com/o3de/o3de-extras/blob/development/CONTRIBUTING.md).

**Comment by adamdbrw** [comment]
@aquav3 are you still willing to contribute this improvement?

**Comment by michalpelka** [comment]
Discussed in sig-simulation issue triage. I keep needs-triage label to issue triage it by sig/ui-ux.

**Comment by jhanca-robotecai** [comment]
The PR that triggered this issue is implemented in https://github.com/o3de/o3de-extras/pull/433

**Comment by adamdbrw** [comment]
The original issue is fixed, this is otherwise low priority. Closing this.
