### ISSUE TITLE
URDF Importer: Single xacro file with multiple configurations

### ISSUE THREAD

**Issue by arturkamieniecki** [o3de/o3de-extras#392]
When importing a robot from an xacro file with a configuration parameter the URDF importer does not take into consideration that the provided robot is different. 

Following the instructions at: https://docs.o3de.org/docs/user-guide/interactivity/robotics/importing-robot/. By changing parameters, we can import different kinds of robots using one file. This process will always create a folder to store meshes in Assets/UrdfImporter. The folder's name depends on the selected file, not the parameters. This will create a problem when importing a different robot with the same file but different arguments, the URDF Importer will use the same meshes, which can create broken prefabs.

Example: importing a Universal Robot.
When importing a ur5 arm and then ur10 URDF importer will use the same meshes.

**Comment by jhanca-robotecai** [comment]
@arturkamieniecki 
@lewandowskikacper 
is the issue solved now? can it be closed?

**Comment by arturkamieniecki** [comment]
Closed with #394 merge.
