### ISSUE TITLE
Joint state publisher publish message that is not supported by MoveIt2 

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de-extras#396]
I've tried to communicate with MoveIt2 connected to the robot simulated in the o3de-physics-test scene (branch test_366).

Unfortunately MoveIt2 client is not happy with JointState message from o3de / ROS2 simulation:
```
/home/michal/ws_paletization/src/hello_moveit/cmake-build-debug/hello_moveit --ros-args -p use_sim_time:=true
[INFO] [1688992796.344297177] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 3024.88 seconds
[INFO] [1688992796.344352979] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
[WARN] [1688992796.355793451] [moveit_ros.robot_model_loader]: No kinematics plugins defined. Fill and load kinematics.yaml!
[INFO] [1688992796.383847823] [move_group_interface]: Ready to take commands for planning group panda_arm.
[INFO] [1688992796.388928443] [moveit_ros.current_state_monitor]: Listening to joint states on topic 'joint_states'
[WARN] [1688992797.489845555] [moveit_ros.current_state_monitor]: No state update received within 100ms of system clock
[WARN] [1688992798.490695641] [moveit_ros.current_state_monitor]: No state update received within 100ms of system clock
[WARN] [1688992799.491512761] [moveit_ros.current_state_monitor]: No state update received within 100ms of system clock
[WARN] [1688992800.492332146] [moveit_ros.current_state_monitor]: No state update received within 100ms of system clock
[WARN] [1688992801.493026894] [moveit_ros.current_state_monitor]: No state update received within 100ms of system clock
[WARN] [1688992802.493725088] [moveit_ros.current_state_monitor]: No state update received within 100ms of system clock
[WARN] [1688992803.494427657] [moveit_ros.current_state_monitor]: No state update received within 100ms of system clock
[WARN] [1688992804.495156244] [moveit_ros.current_state_monitor]: No state update received within 100ms of system clock
````
Moveit2 API complains here : https://github.com/ros-planning/moveit2/blob/c9a9e407b0a27858c8eea838ccbbd389d7109f9e/moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp#L235, please review https://github.com/ros-planning/moveit2/blob/c9a9e407b0a27858c8eea838ccbbd389d7109f9e/moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp#L325. It can be bug in Moveit2 as well.
Here is a simple C++ node to reproduce:

https://gist.github.com/michalpelka/7db321f50f43500d57ce196ebf042f58

**Comment by michalpelka** [comment]
Seems that the subscribe is not spinning. Will investigate. Probably not a bug (at least not in ROS2 gem).

**Comment by Antoni-Robotec** [comment]
Could this warning be related?
```[WARN] [1689087480.501024947] [o3de_ros2_node]: New subscription discovered on topic '/joint_states', requesting incompatible QoS. No messages will be sent to it. Last incompatible policy: RELIABILITY_QOS_POLICY```
It appears (for me) in o3de when running rviz2.

**Comment by adamdbrw** [comment]
@michalpelka advised this might be due to misuse of Moveit. Closing
