### ISSUE TITLE
Create FactoryAutomationGem

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de-extras#406]
ROS2 Gem is growing larger and larger with every week. Good work!

I propose to make a smaller ROS2 Gem and give a new home for some components.

Components to be moved:
 - ConveyorBeltRequests (https://github.com/o3de/o3de-extras/pull/367)
 - ProximitySensor (https://github.com/o3de/o3de-extras/pull/368)
 Assets:
 - Conveyor belt meshes / prefabs.

I propose to create a new Gem (with some assets) called **Factory Simulation**. Consider using break dependency on ROS2 Gem to make the new Gem for non-robotics users.

**Comment by pawelbudziszewski** [comment]
I guess there will be also some new components to be included, e.g. proximity sensor visual.

**Comment by pawelbudziszewski** [comment]
The conveyor line: https://github.com/RobotecAI/ROSCon2023Demo/pull/13
Models and prefabs
