### ISSUE TITLE
Refactor ROS2LidarSensorComponent and ROS2Lidar2DSensorComponent

### ISSUE THREAD

**Issue by jhanca-robotecai** [o3de/o3de-extras#435]
There are two lidar sensor components available in ROS2 Gem: `ROS2LidarSensorComponent` and `ROS2Lidar2DSensorComponent`. Both components share most of the configuration and implementation, which is duplicated in two separate classes. Refactor the code to make it more readable and less duplicated. 

Please note PR #433, which modifies the implementation. This PR should be merged first to reduce the rebase/merge overhead.

**Comment by arturkamieniecki** [comment]
Closed as resolved.
