### ISSUE TITLE
light goes dark in Ros2FleetRobotTemplate

### ISSUE THREAD

**Issue by lewandowskikacper** [o3de/o3de-extras#448]
When working with Warehouse from Ros2FleetRobotTemplate the light in viewport goes dark after launching Game mode a few times.

**Comment by lewandowskikacper** [comment]
This is possibly caused by DiffuseProbeGrid: https://github.com/o3de/o3de/issues/16519

**Comment by michalpelka** [comment]
Solved with https://github.com/o3de/o3de/issues/16519
