### ISSUE TITLE
Provide clear guidance as to what goes into the o3de-extras repository

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/o3de-extras#45]
Please provide in the README:

* A clear description to the point of the repository
* How folks add gems or content here? Who owns accepting work on behalf of O3DE, whats the criteria etc?

**Comment by byrcolin** [comment]
I have a document forthcoming.

**Comment by lmbr-pip** [comment]
Relates to https://github.com/o3de/tsc/issues/57
