### ISSUE TITLE
Robot in Robotic Simulation Template not controllable from RViz2 with ROS 2 Iron distribution selected

### ISSUE THREAD

**Issue by PawelLiberadzki** [o3de/o3de-extras#451]
**To replicate:**
1. Set ROS 2 distribution to Iron.
2. Create or reconfigure project from Robotic Simulation Template, build/rebuild it.
3. Open this project and run simulation - robot should be controllable.
4. Follow steps in [ROS 2 Project example](https://github.com/o3de/o3de-extras/blob/development/Templates/Ros2ProjectTemplate/Template/Examples/slam_navigation/README.md) to launch RViz2. At this step you should get following sequence of logs:

> [bt_navigator-6] [INFO] [1691138616.838803128] [bt_navigator]: Activating
> [bt_navigator-6] [ERROR] [1691138616.839305494] [bt_navigator]: Exception when loading BT: Error at line 14: -> Node not recognized: WouldAPlannerRecoveryHelp
> [bt_navigator-6] [ERROR] [1691138616.839349905] [bt_navigator]: Error loading XML file: /opt/ros/iron/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml
> [lifecycle_manager-9] [ERROR] [1691138616.839646714] [lifecycle_manager_navigation]: Failed to change state for node: bt_navigator
> [lifecycle_manager-9] [ERROR] [1691138616.839691139] [lifecycle_manager_navigation]: Failed to bring up all requested nodes. Aborting bringup.

5. RViz2 shows cloud of points correctly, but 2D Goal Pose tool does not work. Note that messages from RViz2 seem to be sent correctly. Note also, that RViz2 updates viewport correctly, when you control robot manually from the project.

**Additional info**
This template does not work for ROS 2 Iron, but seems to work correctly for ROS 2 Humble.

**Possibility**
May be that we need different navigation param files for Humble and Iron distributions. Launch file for RViz2 (hyperlink in p. 4 above) would then check ROS 2 distribution and select correct param file. Check [#3400](https://github.com/ros-planning/navigation2/pull/3400) and #450 for possible additional info. Moreover, refer to these param files:
https://github.com/ros-planning/navigation2/blob/main/nav2_bringup/params/nav2_params.yaml
https://github.com/o3de/o3de-extras/blob/development/Templates/Ros2ProjectTemplate/Template/Examples/slam_navigation/launch/config/navigation_params.yaml

**Comment by pijaro** [comment]
Iron version of nav2 (a behavior tree to be precise) requires additional plugins to be loaded. 

You must add:

```
      - nav2_would_a_controller_recovery_help_condition_bt_node
      - nav2_would_a_planner_recovery_help_condition_bt_node
      - nav2_would_a_smoother_recovery_help_condition_bt_node
```

to the list of `bt_navigator` plugin list.
