### ISSUE TITLE
There are multiple unecessary warning in URDF importer.

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de-extras#470]
URDF importer during import makes a lot of noise :
https://gist.github.com/michalpelka/69b201c3506dfc8f4ea17a4118cb4965
Some are logic errors in log e.g. : "[Warning] (CreatePrefabFromURDF) - cannot create joint panda_joint7".
Some are warnings from o3de component and rest is only debug. 
Please fix at list logic errors.
It also produce output to system's console.

**Comment by lgleim** [comment]
@michalpelka could it be that this issue has already been addressed by the recent changes?

**Comment by michalpelka** [comment]
Those logic errors were addressed during migration from liburdf to SDFormat.
Some debug output left.
