### ISSUE TITLE
ROS2 Robot Importer cannot import the MoveIt Resouces Robot Models

### ISSUE THREAD

**Issue by lumberyard-employee-dm** [o3de/o3de-extras#472]
As brought up in PR #460 switching to using libsdformat has issues importing some URDF files, that URDFDom is able to import successfully https://github.com/o3de/o3de-extras/pull/460#pullrequestreview-1595595506

Investigate problems importing [panda franka and fanuc](https://github.com/ros-planning/moveit_resources) robots with SDFormat library; double-check the warnings triggered by  [pr2](https://github.com/ros-planning/moveit_resources) import

**Comment by lgleim** [comment]
This issue appears to be resolved by https://github.com/o3de/o3de-extras/pull/481 @michalpelka ?

**Comment by jhanca-robotecai** [comment]
I can confirm the robots are successfully imported with the fix in #481. This issue can be closed.

![image](https://github.com/o3de/o3de-extras/assets/134940295/4561a48a-80a0-4251-aab0-8c56834e8fed)

**Comment by michalpelka** [comment]
@lgleim issue should be closed.
Thanks, @jhanca-robotecai for this test.
