### ISSUE TITLE
RobotImporter cannot apply material data

### ISSUE THREAD

**Issue by jhanca-robotecai** [o3de/o3de-extras#489]
RobotImporter cannot set material data while creating visuals. The issue is most probably related to #486: the entity cannot be activated while importing the robot, hence the [color cannot be set](https://github.com/o3de/o3de-extras/blob/adfadad0279181a7324129ff5993fa37296e6e98/Gems/ROS2/Code/Source/RobotImporter/URDF/VisualsMaker.cpp#L236). 

It works correctly when the same code is implemented as a separate component and added to the entity. It also works when called from a canvas script (I had to change the parameter to `baseColor.color` and get the material ID from the bus by using the name):
![image](https://github.com/o3de/o3de-extras/assets/134940295/6b27ca22-ee37-480d-a976-17af28c9cb40)

The problem can be reproduced using [this model](https://github.com/RobotecAI/o3de-ros2-gem-testing/blob/main/URDFTest/02_IMPORTING_VALID_SIMPLE_URDF/IMPORTING_VALID_SIMPLE_URDF_TESTCASE.md)

**Comment by lumberyard-employee-dm** [comment]
This sounds like the MateriaComponentlRequestBus EBus could be disconnected when the EBus calls occurs for some reason.

One thing that could be done is to use the MateriaComponentlRequestBus::FindFirstHandler to get a pointer to a `MaterialsComponentRequests*` instance and then directly call SetPropertyValue on it.
That would help with debugging.

**Comment by michalpelka** [comment]
Discussed in sig/simulation, added priority, and discussed potential solutions.
