### ISSUE TITLE
Project does not open when Oculus Development Runtime Features are turned on

### ISSUE THREAD

**Issue by LB-KacperSzczepanski** [o3de/o3de-extras#52]
**Describe the bug**
Using Developer Runtime Features via Oculus Link causes issues when launching o3de project. The project and Asset Processor close on their own few seconds after splash screen. Oculus Quest2 is connected by a cable provided with the set and Oculus application shows that the headset is connected but not through USB 3.0. The issue occurs the same way when Quest2 is connected through Oculus Air Link (via Wi-Fi). Adding “-rhi=vulkan -openxr=enable” to command line when launching the editor does not impact the issue.  Please refer to the attached videos for more information.

 **Steps to reproduce**

1. Enter Oculus application.
2. Connect Oculus Quest2 to Oculus application.
3. Click on Settings in menu on the left.
4. In the top row of menu select Beta.
5. Enable Developer Runtime Features.
6. Open o3de Project Manager.
7. Open Editor for selected project.

 
**Expected behavior**
 Level is rendered in a window on display and in the game mode. It is also rendered on Quest 2 as described here https://github.com/o3de/o3de-extras/wiki/Build-and-Run-OpenXR-in-O3DE#running-openxr-with-the-editor
 
**Actual behavior**
 The project does not open. Asset Processor is closing a few seconds after splash screen is shown.
 
**Video**

https://user-images.githubusercontent.com/86953282/200315183-eec8c9a0-2943-44ba-9d7a-f704a8a97845.mp4

https://user-images.githubusercontent.com/86953282/200315216-458d374b-e42f-4e75-926a-8c332b886def.mp4

**Found in Branch**
 Development (181022c)
 
 **Desktop/Device:**
 • Device: PC
 • OS: Windows
 • Version: 10 Pro
 • CPU: Intel Core i7 11700F
 • GPU: Nvidia RTX 3070 LHR
 • Memory: 32GB

**Comment by smurly** [comment]
the USB cable provided with the Quest 2 headset is rated for charging via USB 2.0 and does not meet the USB 3.0+ requirement for data speed of linked used.

you may also set the rhi=vulkan with a setreg file which might also be a place to specify the default project
```
{
    "Amazon": {
        "AzCore": {
            "Bootstrap": {
                "project_path": "D:/workspace/o3de-extras/Projects/OpenXRTest"
            },
        }
    },
    "O3DE": {
        "Atom": {
            "RHI": {
                "FactoryManager": {
                    "factoriesPriority": [ "vulkan" ]
                }
            }
        }
    }
}
```

**Comment by LB-KacperSzczepanski** [comment]
Adding setreg did not impact the issue. We are waiting for cables that are up to specification to verify the issue using those.

**Comment by moraaar** [comment]
@LB-KacperSzczepanski have you received the new cables. Is this issue still happening? 

AFAIK there is no connection between Oculus Development Runtime Features being on and that O3DE editor doesn't open. I think the cause must be different. But I'll hold until this is tested again with new cables.

Once it's retested, if the issue still happens please attach the editor's log (from `<project-path/user/log`>.

Thanks.

**Comment by LB-KacperSzczepanski** [comment]
The issue does happen when cables that are up to specification are used. Closing the issue.
