### ISSUE TITLE
Modification of namespace strategy in ROS2Frame Component causes Editor crash

### ISSUE THREAD

**Issue by lewandowskikacper** [o3de/o3de-extras#525]
Steps:
1. Create new, empty level.
2. Add new entity, add ROS2Frame component to it.
3. Change the namespace strategy (from Default to any other, eg. Empty).

The Editor crashes.

Found in o3de stabilization  [9b90a24479e2b191d2125d34c1984b013b2cb13f](https://github.com/o3de/o3de/commit/3a8376e0b79654fa96d3ee6a767b2eafd9e1fd2e), o3de-extras development  01455c63d99142a279f9a04c0a11d075efebab3a

**Comment by lewandowskikacper** [comment]
This problem can be avoided by settinng `ed_enableDPE=false` in Editor's console.

The problem seems to be related to nullptr dereference somewhere in     
`static QAccessibleInterface *queryAccessibleInterface(QObject *);`

Note: There was a change in defaults regarding DPE recently: https://github.com/o3de/o3de/pull/16699/files.

**Comment by cgalvan** [comment]
This should be fixed by my PR in-flight now: https://github.com/o3de/o3de/pull/16764
