### ISSUE TITLE
[Android] Project generation fails due to Gradle error

### ISSUE THREAD

**Issue by LB-RostyslavGavryliuk** [o3de/o3de-extras#53]
**Describe the bug**
Project generation fails with a Gradle 7.0.2 error message related to not being able to compile settings file 'C:\o3de-build\android\settings.gradle' when running generate_android_project.py.

Full log file: [GrandleOutput.txt](https://github.com/o3de/o3de-extras/files/9952539/GrandleOutput.txt)

**Steps to reproduce**
1. Set up O3DE source engine. (https://www.o3de.org/docs/welcome-guide/setup/setup-from-github/)
2. Clone o3de-extras.
3. Register XR Gems to the engine. (https://github.com/o3de/o3de-extras/wiki/Build-and-Run-OpenXR-in-O3DE)
4. Add [XR_Office](https://github.com/o3de/o3de-extras/tree/development/Projects/OpenXRTest/Levels/XR_Office) project to the Project Manager.
5. Build [XR_Office](https://github.com/o3de/o3de-extras/tree/development/Projects/OpenXRTest/Levels/XR_Office) project.
6. Complete requirements for Android project configuration. (https://www.o3de.org/docs/user-guide/platforms/android/generating_android_project_windows/)
7. Open terminal in %Engine_path%\cmake\Tools\Platform\Android.
8. Run generate_android_project.py with appropriate flags.

**Additional Details**

--oculus-project flag was used for running generate_android_project.py, as Oculus testing was performed when issue was found.

**Expected behavior**
Command completes without errors.

**Actual behavior**
Project generation fails with the Gradle error.

**Found in Branch**
O3DE Development ([181022c](https://github.com/o3de/o3de/commit/181022cc8f7e92557fa831065605784c11015df0))
o3de-extras ([d83f7f7](https://github.com/o3de/o3de-extras/commit/d83f7f7233101a04b2cea4b3d35cc9bc5f71c970))

**Desktop/Device:**
- Device: PC
- OS: Ubuntu
- Version 20.04
- CPU Intel i7-11700F
- GPU Nvidia GeForce RTX 3070
- Memory 32GB

**Comment by amzn-phist** [comment]
One thing... `XR_Office` is the name of the level.  The project is at `Projects/OpenXRTest`.

**Comment by moraaar** [comment]
Never seen that error before:

````
General error during conversion: Unsupported class file major version 63
````

@LB-RostyslavGavryliuk your `generate_android_project.py`:

````
C:\o3de-extras\Projects\OpenXRTest>%O3DE_ENGINE_PATH%\python\python.cmd %O3DE_ENGINE_PATH%\cmake\Tools\Platform\Android\generate_android_project.py --engine-root %O3DE_ENGINE_PATH% --project-path %O3DE_PROJECT_PATH% --build-dir %O3DE_BUILD_ROOT%\android --third-party-path %USERPROFILE%\.o3de\3rdParty --android-sdk-path %O3DE_ANDROID_SDK_PATH% --android-ndk-version %O3DE_ANDROID_NDK_VERSION% --android-sdk-platform %O3DE_ANDROID_SDK_API_LEVEL% --enable-unity-build --include-apk-assets --asset-mode %O3DE_ANDROID_ASSET_MODE%
````

looks good, but please provide the values you set for all those variables. It'll be useful to know them. 

Try adding the following parameters too to specify explicitly what gradle and ninja folders to use and see if that fixes the issue. Example:

`--gradle-install-path C:\Android\gradle-7.0.2 --ninja-install-path C:\Android\ninja-win`

In addition, please provide what version of ninja you've got installed.

Thanks

**Comment by amzn-phist** [comment]
It is possible that it's JDK version related.  I'd suggest installing a JDK v1.8.X and setting `%JAVA_HOME%` and trying again.

**Comment by LB-RostyslavGavryliuk** [comment]
The issue has been worked around, Gradle setup was fine. There was a Java issue present that has been fixed bu simply placing the installation and re-adding a system Variable.
