### ISSUE TITLE
ROS2 Spawners don't work with Articulation Links

### ISSUE THREAD

**Issue by Antoni-Robotec** [o3de/o3de-extras#551]
Using a ROS2 Spawner to spawn entities with articulation links leads to a segfault when exiting the simulation. This could very well be a bug with o3de articulation links, but I don't know how to test it without a ROS2 Spawner.
o3de:
branch development
commit ce640e096521ff376add9917140ea98689230199
o3de-extras:
branch development
57ae343715f807f2ab0419ff54b301d4f036528c
![Screenshot from 2023-09-29 10-44-18](https://github.com/o3de/o3de-extras/assets/138497503/63312655-9fe5-497c-95df-537f81407123)
To replicate:
Create a prefab, even just a single entity with an articulation link will work
Create a ROS2 spawner spawning it
Enter the simulation
Spawn the entity
Exit the simulation

**Comment by michalpelka** [comment]
It is unrelated to ROS2 Gem : https://github.com/o3de/o3de/issues/16990

**Comment by michalpelka** [comment]
It is being fixed on https://github.com/o3de/o3de/pull/17021

**Comment by arturkamieniecki** [comment]
Closed as https://github.com/o3de/o3de/pull/17021 was merged.
