### ISSUE TITLE
RobotImporter fails to import simple urdf

### ISSUE THREAD

**Issue by jhanca-robotecai** [o3de/o3de-extras#560]
RobotImporter fails to import a simple `urdf` file with two links and a fixed joint. It works correctly on `urdf` file with one link only. 
[test_models.zip](https://github.com/o3de/o3de-extras/files/12783750/test_models.zip)

It works correctly on 5185ef0.
Prefab creator stalls on empty screen on 6acba55.
![fail1](https://github.com/o3de/o3de-extras/assets/134940295/94ee89c6-8c97-44bb-a68f-3c294dfa53bd)

Prefab creator complains it cannot create a prefab on 1bba3b7.
![fail2](https://github.com/o3de/o3de-extras/assets/134940295/91849a89-fc03-4525-9b56-c4568a09561a)

Therefore the main suspects are #523 and #547

**Comment by michalpelka** [comment]
I found some issue :
```
michalpelka@mpsimpc:~/github/o3de-extras$ git diff
diff --git a/Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp b/Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp
index 87e5178f..3722cf5d 100644
--- a/Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp
+++ b/Gems/ROS2/Code/Source/RobotImporter/RobotImporterWidget.cpp
@@ -439,10 +439,6 @@ namespace ROS2
         const AZ::IO::Path prefabPath(AZ::IO::Path(AZ::Utils::GetProjectPath()) / prefabPathRelative);
         bool fileExists = AZ::IO::FileIOBase::GetInstance()->Exists(prefabPath.c_str());
 
-        {
-            m_prefabMakerPage->setSuccess(false);
-            return;
-        }
         if (fileExists)
         {
             QMessageBox msgBox;
```
Now I am getting info on created entities, but still no luck with prefab:
```
[Error] (Prefab) - PrefabLoader::SaveTemplateToFile - Failed to save template 'Levels/www/www.prefab' to location '/home/michalpelka/github/ROSCon2023Demo/Project/Assets/Importer/004_husky.prefab'.Error: Relative path 'Assets/Importer/004_husky.prefab' for location didn't match template name.
```

**Comment by michalpelka** [comment]
#523 gives empty entites list (as in first screenshot).
#547 fixing bug, allows prefab makere to continue, but gives error:
```[Error] (Prefab) - PrefabLoader::SaveTemplateToFile - Failed to save template 'Levels/www/www.prefab' to location '/home/michalpelka/github/ROSCon2023Demo/Project/Assets/Importer/004_husky.prefab'.Error: Relative path 'Assets/Importer/004_husky.prefab' for location didn't match template name.```
