### ISSUE TITLE
OpenXRTest project does not launch as described in the documentation

### ISSUE THREAD

**Issue by LB-RostyslavGavryliuk** [o3de/o3de-extras#58]
**Describe the bug**
OpenXRTest project cannot be opened in Editor with -rhi=vulkan -openxr=enable flags and Oculus link established, as mentioned in https://github.com/o3de/o3de-extras/wiki/Build-and-Run-OpenXR-in-O3DE. Editor Launching screen is present in Oculus before a crash occurs. The issue originally was occurring on two machines [DxDiag1.txt](https://github.com/o3de/o3de-extras/files/9981450/DxDiag.txt), [DxDiag2.txt](https://github.com/o3de/o3de-extras/files/9981491/DxDiag.txt) but after processing the assets before starting the project, it was fixed on one of them [DxDiag1.txt](https://github.com/o3de/o3de-extras/files/9981431/DxDiag.txt). The issue did not occur on another machine at all [DxDiag3.txt](https://github.com/o3de/o3de-extras/files/9981427/DxDiag.txt).

**Additional details**
Latest updates Windows 11 and latest Nvidia drivers are used. Testing performed with Oculus Link via both cable and air. XR gems have been registered and enabled in OpenXRTest\Registry\OpenXR.setreg.

Logs:
[Editor.log](https://github.com/o3de/o3de-extras/files/9981370/Editor.log)
[error.log](https://github.com/o3de/o3de-extras/files/9981371/error.log)
[error.zip](https://github.com/o3de/o3de-extras/files/9981389/error.zip)

**Steps to reproduce**
1. Complete O3DE system requirements. (https://www.o3de.org/docs/welcome-guide/requirements/)
 2. Setup O3DE from Github (https://www.o3de.org/docs/welcome-guide/setup/setup-from-github/)
3. Complete Open XR setup (https://github.com/o3de/o3de-extras/wiki/Build-and-Run-OpenXR-in-O3DE)
 4. Add and build the OpenXRTest project.
5. Enable OpenXR in OpenXRTest\Registry\OpenXR.setreg.
6. Establish Oculus link.
7. Attempt to launch the Editor with -rhi=vulkan -openxr=enable flags as mentioned in https://github.com/o3de/o3de-extras/wiki/Build-and-Run-OpenXR-in-O3DE.

**Expected behavior**
Editor launches with Oculus.

**Actual behavior**
Editor crashes after assets are processed.

Call Stack Trace:
25) 00007FFB7E2702E7 (KERNELBASE) : UnhandledExceptionFilter
24) 00007FFB7D94D6D8 (InProcessClient64) : (function-name not available)
23) 00007FFB7D94D321 (InProcessClient64) : (function-name not available)
22) 00007FFB806F5530 (ntdll) : memset
21) 00007FFB806DC876 (ntdll) : _C_specific_handler
20) 00007FFB806F241F (ntdll) : _chkstk
19) 00007FFB806A14A4 (ntdll) : RtlRaiseException
18) 00007FFB806F0F4E (ntdll) : KiUserExceptionDispatcher
17) C:\o3de-extras\Gems\XR\Code\Source\XRSystem.cpp (188) : XR::System::GetNumViews
16) C:\o3de\Gems\Atom\RPI\Code\Source\RPI.Public\WindowContext.cpp (208) : AZ::RPI::WindowContext::CreateSwapChains
15) C:\o3de\Gems\Atom\RPI\Code\Source\RPI.Public\ViewportContext.cpp (27) : AZ::RPI::ViewportContext::ViewportContext
14) C:\o3de\Gems\Atom\RPI\Code\Source\RPI.Public\ViewportContextManager.cpp (152) : AZ::RPI::ViewportContextManager::CreateViewportContext
13) C:\o3de\Gems\Atom\Tools\AtomToolsFramework\Code\Source\Viewport\RenderViewportWidget.cpp (66) : AtomToolsFramework::RenderViewportWidget::InitializeViewportContext
12) C:\o3de\Code\Editor\EditorViewportWidget.cpp (829) : EditorViewportWidget::SetViewportId
11) C:\o3de\Code\Editor\ViewPane.cpp (304) : CLayoutViewPane::AttachViewport
10) C:\o3de\Code\Editor\ViewPane.cpp (220) : CLayoutViewPane::SetViewClass
 9) C:\o3de\Code\Editor\LayoutWnd.cpp (205) : CLayoutWnd::MaximizeViewport
 8) C:\o3de\Code\Editor\LayoutWnd.cpp (515) : CLayoutWnd::LoadConfig
 7) C:\o3de\Code\Editor\MainWindow.cpp (445) : MainWindow::InitCentralWidget
 6) C:\o3de\Code\Editor\MainWindow.cpp (470) : MainWindow::Initialize
 5) C:\o3de\Code\Editor\CryEdit.cpp (1740) : CCryEditApp::InitInstance
 4) C:\o3de\Code\Editor\CryEdit.cpp (4006) : CryEditMain
 3) C:\o3de\Code\Editor\main.cpp (32) : main
 2) D:\github\3p-package-source\package-system\Qt\temp\src\qtbase\src\winmain\qtmain_win.cpp (97) : WinMain
 1) d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl (288) : __scrt_common_main_seh

**Found in Branch**
O3DE Development (522b935)
o3de-extras ([3dee66e](https://github.com/o3de/o3de-extras/commit/3dee66ea9802b370a8ad82134f76d6f81919beaa))

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version 11
- CPU Intel i7-11700F
- GPU Nvidia GeForce RTX 3070
- Memory 32GB

**Comment by moraaar** [comment]
The log shows it's crashing when trying to access to the xr swapchain, which is null. That means xr swapchains weren't created correctly, which most likely reasons are: vulkan is not used or device was not connected with Link  connection established. But the steps do say both things happened.

@LB-BartoszDudzinski please do the following tests for me:
- Change `OpenXRTest\Registry\OpenXR.setreg` please disable openxr.
- Then run the editor with no parameters. That should just work, it should open the editor with DX12 and no OpenXR.
- Then run the editor with just the parameter `-rhi=vulkan`. That should work too, it should open the editor with Vulkan and no OpenXR.

Please verify these work for you. This way we can exclude basic setup errors.

**Comment by moraaar** [comment]
Thanks @LB-HubertUberman, closing issue based on the above comment.
