### ISSUE TITLE
Lidar does not refresh settings

### ISSUE THREAD

**Issue by jhanca-robotecai** [o3de/o3de-extras#585]
When adding a lidar, it does not work until some options are changed and changed back.

o3de: `main`, 0d490a2b4b5e04fd17edf4850c91f94361d4b836
o3de-extras: `main`, 6d79155f6d2f904a382b9bfe0ee21e67395d29b4
ROSCon2023 demo: `main`, b48ecc97202f1ae915381c4231bcd3ca31e39a6e

It should be first checked if the same issue exists on `development` branch.

Reproduce: 
1. [Import robot](https://github.com/RobotecAI/o3de-ros2-gem-testing/blob/main/URDFTest/07_IMPORTING_ROSBOT/IMPORTING_ROSBOT_TESTCASE.md)
2. Add lidar to _laser_ entity, set ignored layer to 2 (this ignored layer was added earlier, but it does not matter)
3. Add colliders of the casing to the same ignored layer to avoid self-collisions
4. Run game - the lidar does not work; exit game mode
5. Switch lidar to `RGL`, run game, lidar works
6. Switch lidar back to  `scene queries`, run game, lidar works

Video:
https://github.com/o3de/o3de-extras/assets/134940295/739e5863-c945-4b60-989d-ae17e8bc5acd

**Comment by jhanca-robotecai** [comment]
Cannot reproduce the issue on the `development` branches (both o3de and o3de-extras) using _ROS2ProjectTemplate_, it should be verified if the problem occurs on a different machine.

**Comment by arturkamieniecki** [comment]
Closed with #590.
