### ISSUE TITLE
RobotImporter incorrectly adding Robot Control component to non-robot imports

### ISSUE THREAD

**Issue by jhanca-robotecai** [o3de/o3de-extras#610]
**Describe the bug**
`RobotControl` component is added to the first link of the first model while importing data from URDF/SDFormat. This is an incorrect behavior for non-robot imports. In the previous release, _RobotImporter_ was used to import URDF files with a single robot only. This is not the case anymore, as _RobotImporter_ can parse SDFormat data with multiple models (robots) or even worlds. E.g. `RobotControl` component is added to _air conditioning_ link when importing [aws-bookstore-world](https://github.com/aws-robotics/aws-robomaker-bookstore-world).

It could be also considered to rename _RobotImporter_ into something more generic.

**Expected behavior**
Do not add `RobotControl` component when not needed.

**Actual behavior**
`RobotControl` component is added to the first link of the first model.

**Comment by michalpelka** [comment]
It is quite easy to remove technical debt. I would recommend removing this behavior of creating robot control both for URDF and SDFs. What are your thoughts @adamdbrw @amzn-mike @lumberyard-employee-dm .

**Comment by adamdbrw** [comment]
How about adding this component to each robot  based on control plugin? This seems correct

**Comment by jhanca-robotecai** [comment]
> How about adding this component to each robot based on control plugin? This seems correct

I am fine with that and I would suggest the same, however, it requires `<gazebo>` tags in robot description files or manual addition of _Robot Control Component_ after the import.
