### ISSUE TITLE
Multiplayer Template Requires Blast Gem

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de-extras#612]
Multiplayer Template requires Blast gem, which is not included in the latest release of O3D

**Steps to reproduce**
1. Open project manager
2. New Project... > Create New Project
3. Create a new Multiplayer project
 (You may need to click "Add remote Template" and add _https://github.com/o3de/o3de-extras.git_ to see Multiplayer template as an option)
4. Build new project

**Expected behavior**
Multiplayer Template builds

**Actual behavior**
Multiplayer template cannot be built because it's missing a gem

**Work Around**
Remove Blast gem from the template by editing the gem dependencies in Project Manager.
Blast isn't actually used for any features in the Multiplayer Template

**Found in Branch**
O3DE point-release/23101
4219baae7e01f14314d9d1f4623fcc888fb9debd

**Comment by drakeredwind01** [comment]
suggest adding `triage/accepted`

**Comment by ShaunaGordon** [comment]
Fixed by in #680

**Comment by jhanca-robotecai** [comment]
I will close the issue as fixed.
