### ISSUE TITLE
Add a possibility to despawn entities

### ISSUE THREAD

**Issue by zakmat** [o3de/o3de-extras#618]
**Is your feature request related to a problem? Please describe.**
I would like to have a way to de-spawn entities that were spawned during the simulation when they are no longer relevant. This is especially important for cases where entities are complex e.g. when they are publishing multiple topics under different namespaces and or when new entities are periodically spawned during the simulation run.

**Describe the solution you'd like**
Two scenarios I have in mind are a de-spawn after preconfigured time or after reaching special area marked as a de-spawn point.

**Describe alternatives you've considered**
Possible alternative would be to move entity away from the scene/deactivate it or even maintain the list of entities for future use. But this logic seem more complex than removing entities when no longer needed.

**Comment by arturkamieniecki** [comment]
One solution is to create an additional service, similar to the spawn service, that would despawn the entity.
