### ISSUE TITLE
Lighting issue is present in the XR_Office level when run as an application in Oculus

### ISSUE THREAD

**Issue by LB-RostyslavGavryliuk** [o3de/o3de-extras#66]
**Describe the bug**
Lighting issue can be seen in the XR_Office level when deployed to Oculus goggles as an APK. This issue also occurs when using GameLauncher, however does not occur when opening the level in the Editor.

**Steps to reproduce**
1. Complete O3DE system requirements. (https://www.o3de.org/docs/welcome-guide/requirements/)
2. Setup O3DE from Github (https://www.o3de.org/docs/welcome-guide/setup/setup-from-github/)
3. Complete Open XR setup (https://github.com/o3de/o3de-extras/wiki/Build-and-Run-OpenXR-in-O3DE)
4. Add and build the OpenXRTest project.
5. Enable OpenXR in OpenXRTest\Registry\OpenXR.setreg.
6. Deploy the APK to Oculus (https://www.o3de.org/docs/user-guide/platforms/android/generating_android_project_windows/)

**Expected behavior**
No lighting issues are present when running the APK on Oculus.

**Actual behavior**
Lighting issue can be seen.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/86951905/202727332-52028283-4432-4755-9ddd-004e07f8402e.png)

**Found in Branch**
O3DE Development (daed680)
o3de-extras ([a723dd6](https://github.com/o3de/o3de-extras/commit/a723dd6c2db7d9b35036eee21fe2e3c4c829d392) )

**Desktop/Device:**
- Device: PC / Oculus Quest 2
- OS: Windows
- Version 11
- CPU Intel i7-11700F
- GPU Nvidia GeForce RTX 3070
- Memory 32GB

**Comment by moraaar** [comment]
From @moudgils :

_This is the correct look at the moment. The roof is dark because no lights are pointing up and it gets lit from an image based light which comes from the "FakeGI" entity in the level. But it is not getting applied in the GameLauncher and only works in Editor or when the gamelauncher is launched within the editor. I think the newly proposed changes by Starr should be able to address this._

Assigning to @shawstar so he can improve the lighting of the level.

**Comment by shawstar** [comment]
I am currently Blocked on this as I can not get the XRgem to build. Although, building O3DE, It seems I can get the XR gem to build, but then I can not get the project past Asset Processor, it will keep crashing. 
Attempting, to try and unblock myself..

**Comment by shawstar** [comment]
![image](https://user-images.githubusercontent.com/87207603/203170349-48206a1e-7ade-41e6-bfda-1a4aaf00b3a8.png)
[CMakeLists.txt](https://github.com/o3de/o3de-extras/files/10061044/CMakeLists.txt)

**Comment by shawstar** [comment]
Here you go! A fix, and this will be MUCH faster. :D https://github.com/o3de/o3de-extras/pull/68

**Comment by moraaar** [comment]
Fixed by #68

**Comment by moraaar** [comment]
> I am currently Blocked on this as I can not get the XRgem to build. Although, building O3DE, It seems I can get the XR gem to build, but then I can not get the project past Asset Processor, it will keep crashing.
Attempting, to try and unblock myself..

About this issue, @shawstar was building the OpenXRTest project through an installed O3DE engine, and using Project Manager to do the build. His workaround was to add `LY_DISABLE_TEST_MODULES` cache variable to CMake GUI with value TRUE, but the issue will be fixed by https://github.com/o3de/o3de/pull/13342

**Comment by LB-RostyslavGavryliuk** [comment]
Issue occurs on [974d946](https://github.com/o3de/o3de-extras/commit/974d946a0df3bcbb0f1ae76303d81c9fb55881a5), latest Development, Source build engine was used to build the Project. Here are a few screenshots:

![org o3de (1)](https://user-images.githubusercontent.com/86951905/203518722-8e7e522b-7a05-4093-b8c4-6ee5183665bd.jpg)
![org o3de (2)](https://user-images.githubusercontent.com/86951905/203518724-eea0f8e4-66fe-4e31-be08-b44c11054345.jpg)

**Comment by shawstar** [comment]
Humm, Here is the current set-up after pulling Dev branch > 
![image](https://user-images.githubusercontent.com/87207603/203584330-4fce262a-46c6-46a7-aed4-d76a80563d7a.png)
Seems like some materials and this and that were disconnected.

But... this not the same model that is above in the Quest Screen Shots, Blinds are still in the Room mesh and the lights are totally different. Maybe there is Cache that needs to be cleared?

**Comment by LB-RostyslavGavryliuk** [comment]
Closing the issue, shadows are fixed, after correctly generating a new APK!
