### ISSUE TITLE
Physx Debug not working for Robot Prefab in the Manipulation Template

### ISSUE THREAD

**Issue by utk-hua** [o3de/o3de-extras#669]
**Describe the bug**
While using Physx debug tools in Game mode of the robotic manipulation template, enabling visualizations, collisions, contact etc. 
The joints, articulation, mesh collider components of the robot are not visualized. 

**Assets required**
O3DE Robotic Manipulation Template

**Steps to reproduce**
1. Build the O3DE Engine with PhysX 5 enabled. (point-release/23102)
2. Download o3de-extras ROS Gem (point-release/23102 ) and register with the engine.
3. Start a project based on the Robotic Manipulation Template, open the RoboticManipulation level.
4. Go to the game mode.
5. Press (~) to go to the debug mode.
6. Click on Physx Debug 
7. Click on any visualization you want, the robot arm components are not visualized.

**Expected behavior**
Joints, Colliders of the robot prefab to be visualized

**Actual behavior**
Physics components of other entities in the environment are visualized, but there are no visualizations for the robot prefab.

**Screenshots/Video**

**Found in Branch**
point-release/23102

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) and [o3de/o3de-extras](https://github.com/o3de/o3de-extras) repositories**

o3de : e22213ea946932dc2f94d9f1392e98b4bf2b2c3f
o3de-extras : e2426a4242e9fd11c7b902f6aff3379af06d3556

**Desktop/Device (please complete the following information):**

- Device: PC
- OS: Linux Ubuntu 22.04
- Kernel: 6.5.0-15-generic
- CPU : Intel i7-13700KF
- GPU : Nvidia RTX 4090
- Memory : 128GB

**Comment by lumberyard-employee-dm** [comment]
@utk-hua I believe you need to enable PhysX 5 for the Robotic Workflow using ROS2 to work correctly for manipulation.
That can be done at the CMake configure step by setting the CMake cache variable of AZ_USE_PHYSX5.

The workaround is only needed temporarily as the Phys Gem is being split into both a PhysX 4 and PhysX 5 version as of this [PR](https://github.com/o3de/o3de/pull/17436) by @spham-amzn

**Comment by utk-hua** [comment]
@lumberyard-employee-dm thanks for your reply! forgot to mention that I have built the engine with physx5 enabled. I have updated it in the description.

**Comment by jhanca-robotecai** [comment]
I did a fresh build using o3de/o3de-extras 2310.2 (same commits as yours) and the template worked correctly for me. Maybe your problem is caused by #668?

[debug.webm](https://github.com/o3de/o3de-extras/assets/134940295/e95d68ad-09cd-4e78-aca9-875570e5b513)

**Comment by michalpelka** [comment]
Hello @utk-hua did you managed to run articulated robot with guidance from Jan?
Please give us feedback to have this issue concluded.

**Comment by jhanca-robotecai** [comment]
I will close the issue due to no response. Please reopen if you still have any problems.
