### ISSUE TITLE
[ROS 2] Add quos configuration in the constructor of TopicConfiguration

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de-extras#732]
I would like to construct a publisher for some metadata, but it is by default created as "sensor_qos". It can be change later by user, but it would be great if it could be set by default in my component.

**Describe the solution you'd like**
- add constructor with quos to ROS2::TopicConfiguration
- or add SetQoS method

**Comment by jhanca-robotecai** [comment]
I am closing the issue, it is solved by the PR #738
