### ISSUE TITLE
ROS2 Gem crashes with the development version of O3DE.

### ISSUE THREAD

**Issue by arturkamieniecki** [o3de/o3de-extras#743]
**Describe the bug**
O3DE crashes with the ROS2 Gem. 

**Assets required**
O3DE branch development (4ef9f4ddf6703e0c462348e5d96304f0c89fb7d0), o3de-extras ROS2 Gem (119fdb10ef0b22d803927447f25eaed51c496556)

**Steps to reproduce**
1. Create a project with the ROS2 Gem
2. Build a project
3. Lunch the Editor

**Expected behavior**
The Editor launches

**Actual behavior**
The Editor crashes (segfault)

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
Development O3DE, development o3de-extras

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) and [o3de/o3de-extras](https://github.com/o3de/o3de-extras) repositories**
O3DE - 4ef9f4ddf6703e0c462348e5d96304f0c89fb7d0
o3de-extras ROS2 Gem - 119fdb10ef0b22d803927447f25eaed51c496556

**Desktop/Device (please complete the following information):**
 - Device: Laptop
 - OS: Ubuntu 22.04.4 LTS

 - Version Ubuntu 22.04.4 LTS
 - CPU 12th Gen Intel® Core™ i7-12700H
 - GPU GeForce RTX 3070 Mobile / Max-Q
 - Memory 32.0 GiB

**Comment by michalpelka** [comment]
It is important to check it against the latest and greatest development.

**Comment by arturkamieniecki** [comment]
Tested with o3de-extras development (b18f827f0cbe4a54eec79741a3112c1cab9a793d) and O3DE development(deed71716d70d7d9cd490867e977780b9b47dcc0).

Works as intended.
Closing the issue as it is no longer valid.
