### ISSUE TITLE
ROS 2 Gem Camera - No diffuse probe grid.

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de-extras#748]
**Describe the bug**
ROS 2 camera does not support diffuse probe grid.
**Assets required**
A sample level:
https://gist.github.com/michalpelka/e01d0ebe4cbbaf134fa5756839237b0b

**Steps to reproduce**
1. Go To Editor
2. Open Level
3. Start game
4. Has ugly image in ROS 2 :(

**Expected behavior**
Diffuse probe grid works
![image](https://github.com/user-attachments/assets/c25f36c0-5c04-4e9e-80f3-439c76edbf57)

**Actual behavior**
Diffuse probe does not work:
![image](https://github.com/user-attachments/assets/cfb2222c-576d-422b-8759-cbd2ad7e712c)

**Found in Branch**
o3de : commit dfbc5d341a126a704bb54833ff13054e0bab2c9f (origin/stabilization/2409)
o3de-extras: commit bbaece1ea302726d24db069d1e97755091ae1ba3 (HEAD -> stabilization/2409, origin/stabilization/2409)

**Desktop/Device (please complete the following information):**
 - Device:  PC
 - OS: Ubuntu
 - Version 2204
 - CPU13th Gen Intel(R) Core(TM) i9-13900K
 - GPU RTX 4080
 - Memory 64 GB.

**Comment by jhanca-robotecai** [comment]
This problem is fixed in #749
