### ISSUE TITLE
ROS 2 RobotImporter: Correct procedure of moving Imported prefab into an Asset-only gem.

### ISSUE THREAD

**Issue by Mechazo11** [o3de/o3de-extras#753]
**Describe the bug**
Hello, 

I am trying to create a stand-alone robot asset gem similar to the [ProteusRobot](https://github.com/o3de/o3de-extras/tree/development/Gems/ProteusRobot). 

To this effect, I compiled the [Canadarm2 demo](https://github.com/space-ros/simulation/tree/main/models/canadarm) from ```Space-ROS``` and created a prefab from its URDF and mesh files. 

The robot entity is imported correctly as shown below

![okay](https://github.com/user-attachments/assets/cbf3b6f1-c058-4fcb-91dd-e936a9e23099)

```tree
.
└── /home/O3DE/
    └── /Projects/
        └── /RobotSim/
            └── /Assets/
                ├── /Importer/
                │   └── SSRMS_Canadarm2.prefab
                └── /UrdfImporter/
                    └── 3003611216_SSRMS_Canadarm2/
                        └── ...
```

Now I created a new Gem ```ArmTestGem``` using the Asset template, register it to the engine and then copied ```Importer``` and ```UrdfImporter``` into the Gem's asset folder as follows

```tree

.
└── /home/O3DE/
    ├── /Gems/
    │   └── /ArmTestGem/
    │       └── /Assets/
    │           ├── /Importer/
    │           │   └── SSRMS_Canadarm2.prefab
    │           └── /UrdfImporter/
    │               └── 3003611216_SSRMS_Canadarm2/
    │                   └── ...
    └── /Projects/
        └── /RobotSim/
            ├── /Assets/
            │   └── empty
            └── /Other folders
```

ArmTestGem's ```gem.json``` is configured as follows

```json
{
    "gem_name": "ArmTestGem",
    "version": "1.0.0",
    "display_name": "ArmTestGem",
    "license": "License used i.e. Apache-2.0 or MIT",
    "license_url": "Link to the license web site i.e. https://opensource.org/licenses/Apache-2.0",
    "origin": "The name of the originator or creator",
    "origin_url": "The website for this Gem",
    "type": "Asset",
    "summary": "A short description of this Gem",
    "canonical_tags": [
        "Gem"
    ],
    "user_tags": [
        "ArmTestGem"
    ],
    "platforms": [
        ""
    ],
    "icon_path": "preview.png",
    "requirements": "Notice of any requirements for this Gem i.e. This requires X other gem",
    "documentation_url": "Link to any documentation of your Gem",
    "dependencies": [
        "ROS2>=3.1.0"
],
    "repo_uri": "",
    "compatible_engines": [
        "o3de-sdk>=2.3.0",
        "o3de>=2.3.0"
    ],
    "engine_api_dependencies": [],
    "restricted": "ArmTestGem"
}

```

Now after building the project and launching the Editor, I try to initiate a Canadarm prefab and get the following 

![broken](https://github.com/user-attachments/assets/fb08bc52-ddcc-41bb-9c78-ef16dc9393a4)

In the terminal, I am getting these error/warning messages

```console

<19:16:02> [Warning] (AssetManager) - GetAsset called for asset which does not exist in asset catalog and cannot be loaded. Asset may be missing, not processed or moved. AssetId: {FE4B2B4D-686C-5CC7-9E72-295DDC207997}:10cbfce1
<19:16:02> [Warning] (AssetManager) - GetAsset called for asset which does not exist in asset catalog and cannot be loaded. Asset may be missing, not processed or moved. AssetId: {A990E4B9-4B97-5C0D-A26D-67F31D737D3B}:1b84d668
<19:16:02> [Warning] (AssetManager) - GetAsset called for asset which does not exist in asset catalog and cannot be loaded. Asset may be missing, not processed or moved. AssetId: {CC874A00-37FE-5AE0-BF81-9B9FF9AE45A7}:6cd88b3b
<19:16:02> [Warning] (AssetManager) - GetAsset called for asset which does not exist in asset catalog and cannot be loaded. Asset may be missing, not processed or moved. AssetId: {BF53E985-4C2B-51BF-9D92-4963FEBF199C}:108b18ca
<19:16:02> [Warning] (AssetManager) - GetAsset called for asset which does not exist in asset catalog and cannot be loaded. Asset may be missing, not processed or moved. AssetId: {C3FF656F-3123-5A8A-8B9E-84CBB5623891}:65750910
<19:16:02> [Warning] (AssetManager) - GetAsset called for asset which does not exist in asset catalog and cannot be loaded. Asset may be missing, not processed or moved. AssetId: {36335B2F-FBFD-5FD0-8B84-297A59C3A95A}:bab485bc
<19:16:02> [Warning] (AssetManager) - GetAsset called for asset which does not exist in asset catalog and cannot be loaded. Asset may be missing, not processed or moved. AssetId: {FABEC8A9-146D-529D-BA03-7EC615819735}:43d151fb
<19:16:02> [Warning] (AssetManager) - GetAsset called for asset which does not exist in asset catalog and cannot be loaded. Asset may be missing, not processed or moved. AssetId: {DAC0520F-855F-5F3F-AA47-941E9687C5B0}:10205dda
<19:16:02> [Warning] (AssetManager) - GetAsset called for asset which does not exist in asset catalog and cannot be loaded. Asset may be missing, not processed or moved. AssetId: {6A286C27-1390-5A79-96F5-4456BD1693E0}:10b42f74
<19:16:02> [Warning] (AssetManager) - GetAsset called for asset which does not exist in asset catalog and cannot be loaded. Asset may be missing, not processed or moved. AssetId: {4015F804-FEF8-57EC-BF2F-1B4F590FE6A3}:108466b5
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:02> [Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.
<19:16:48> [Warning] (Prefab) - Missing Prefab 'Importer/SSRMS_Canadarm2.prefab'. 1 instance(s) exist in the level. Save the prefab to restore the file, or delete all instances to resolve this warning.
```

Given we can import a robot to create its prefab what are the next steps in creating a stand-alone Gem?

**Assets required**
[ArmTestGem](https://github.com/Mechazo11/ArmTestGem/tree/main/Assets), ```RO2 Gem```, a project created from ```Ros2ProjectTemplate```

**Steps to reproduce**
2. Click on '...'
3. Select attached asset '...'
4. Scroll down to '...'
5. See error

**Expected behavior**
Initiating a prefab of the stand-alone Asset gem would import the robot model correctly.

**Actual behavior**
Robot model is missing entities and mesh

**Found in Branch**
"development"

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Ubuntu 22.04
 - CPU Ryzen 5600x
 - GPU RTX 3080
 - Memory 32GB

**Additional context**
A similar pipeline was demonstrated by Anido [here](https://github.com/Ekumen-OS/andino_o3de)

**Comment by jhanca-robotecai** [comment]
Hello, thank you for posting the issue. 
Assets such as materials and meshes are stored within prefab with `uuid` numbers rather than paths (you might want to have a look inside of the prefab with a text editor - it is a json file). The `uuid` numbers are regenerated by the asset processor when moving files to a different location. As a result, your prefab cannot find the file anymore. You need to double-click on a prefab to get into _Edit mode_, find the meshes again, and save the prefab.

![image](https://github.com/user-attachments/assets/f741b3c2-ad12-429c-9be9-c550982d2778)

Please let me know if this helps.

**Comment by Mechazo11** [comment]
Dr. @jhanca-robotecai thank you very much. I will try it out and get back to you as soon as I am able.

**Comment by Mechazo11** [comment]
@jhanca-robotecai sir, if I understood your instructions correctly I need to manually select the mesh (```.dae```) files for all these components

![image](https://github.com/user-attachments/assets/a25842cc-7f0a-4c5a-a840-2a7577b9debc)

Is there any programmatic way of achieving this?

**Comment by Mechazo11** [comment]
@jhanca-robotecai, sir, manually selecting the ```.dae``` files seems to update both the prefab and also the Gem itself. I tested this by deleting the prefab I was working on and again spawning a new instance which seems to retain the changes made earlier.

I am attaching a few screenshot with my success with the curiosity rover prefab

![select_prefab](https://github.com/user-attachments/assets/29c2d971-5c52-4f9e-9a96-9d554f8d584c)

After selection

![after_selection](https://github.com/user-attachments/assets/048c4c0e-f239-4d70-9e76-14bb4506aec9)

I am tentatively closing this issue as I think I am now successful in officially creating a new (work in progress) prefab for the curiosity rover. Looking over to the urdf files, I am inclined to believe a version of the robot importer may be possible that will take input the main XACRO file and re-pair meshes to components again to solve the above problem programmatically. I can help with this tool creation but would need some guidance on where to get started.

With best,
@Mechazo11
