### ISSUE TITLE
ROS2Spawner crashes simulation when request contain zero-lenght quaternion

### ISSUE THREAD

**Issue by patrykantosz** [o3de/o3de-extras#757]
**Describe the bug**
When ros2 spawn request contain orientation set to `orientation: { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }` then simulation will crash due to unhandled edge case in ROS2Spawner component. 

**Steps to reproduce**
1. Create an entity with ROS2Spawner Component.
2. Configure ROS2Spawner Component with any spawnable object.
3. Send spawn request via ros2 interface. Example:
   `ros2 service call /spawn_entity gazebo_msgs/srv/SpawnEntity "{name: 'robot', xml: '', robot_namespace: '', initial_pose: { position: { x: 30.58966, y: 30.192916, z: 0.0 }, orientation: { x: 0.0, y: 0.0, z: 0.0, w: 0.0 } }, reference_frame: 'wgs84' }"`

**Expected behavior**
Warning/error message from ROS2Spawner Component, spawn action aborted.

**Actual behavior**
Simulation crashes.

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Ubuntu 22.04

 - CPU i5-12500H
 - GPU RTX4060
 - Memory 64GB

**Comment by michalpelka** [comment]
It was fixed in https://github.com/o3de/o3de-extras/pull/762.
