### ISSUE TITLE
Sky Atmosphere does not work with ROS 2 camera sensor

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de-extras#793]
**Describe the bug**
I am trying to build a level where there is a [Sky Atmosphere](https://www.docs.o3de.org/docs/user-guide/components/reference/atom/sky-atmosphere/) component with ROS 2 camera component. 
**Assets required**
setreg:
```
{
    "O3DE":
    {
        "InputSystem":
        {
            "Mouse":
            {
                "CaptureMouseCursor": false
            }
        },
        "ROS2":
        {
            "SteadyClock" : true,
            "Camera":
            {
                "AllowPipelineModification": true
            }
        }
    }
}
```
and level:
https://gist.github.com/michalpelka/8981b44e4a32077c5dda8586ecca7379

**Steps to reproduce**
1. Create level with Sky Atmosphere and ROS 2 camera component
2. Start game mode in Editor
3. observe that main camera has no atmosphere and ROS 2 camera has one.
4. go to edit mode
5. experience crash

**Expected behavior**
Both main view and ROS 2 camera should provide image with atmosphere, no crashes, vulkan errors.

**Actual behavior**
Only one ROS 2 camera has atmosphere, main windows has no camera. Application crashes.
 
**Screenshots/Video**
![image](https://github.com/user-attachments/assets/a8b30ecc-8020-41a2-b676-a92be72a7f99)
![image](https://github.com/user-attachments/assets/469c1731-21f4-4b0a-b93c-5bbd4952b71c)
**Found in Branch**
Name of or link to the branch where the issue occurs.

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de)**
o3de : 
commit e8570f9d635c0abbf3d733d0524a3c0ae75d726c (HEAD, tag: 2409.0, origin/main)
o3de-extras:
commit 7801ad734e53396829ab1f5e8944824564e47a98 (HEAD, tag: 2409.1, origin/main)

**Desktop/Device (please complete the following information):**
 - Device: [e.g. PC, Mac, iPhone, Samsung] 
 - OS: [e.g. Windows, macOS, iOS, Android, Linux, including distribution and version (e. g. Ubuntu 22.04 / Windows 11 22H2)]

 - Version Ubuntu 22.04, ROS 2 Humble
 - CPU 13th Gen Intel(R) Core(TM) i9-13900K
 - GPU  NVIDIA GeForce RTX 4080 
 - Memory [96GB]

**Additional context**
log with rhi-validation:
https://gist.github.com/michalpelka/e8c6a3557c0ce08393241bb38e8eaaf2

**Comment by arturkamieniecki** [comment]
This PR might close this issue: https://github.com/o3de/o3de/pull/18476#pullrequestreview-2451958544.

**Comment by michalpelka** [comment]
Should be fixed with https://github.com/o3de/o3de/pull/18476#pullrequestreview-2451958544
